### ISSUE TITLE
Recipient receiving multiple identical emails

### ISSUE THREAD

**Issue by MasterX28** [pentestgeek/phishing-frenzy#137] opened 2015-01-08 22:57 UTC
Hello,

I have created a test campaign in production mode and noticed that every time I send out emails for the campaign, the target receives several of the same email (3-5 usually). I do not have the issue when in development mode. Those who I have tested this on knew something was phishy (hehe) because of the multiple emails. Do I have an incorrect configuration somewhere?

Thank you.

**Comment by boredaussie** [comment] 2015-01-12 01:38
I am having this issue as well, however my recipients are receiving duplicated emails (2 for every 1 sent) in development mode. I have not attempted to migrate to production mode as of yet. I've done some testing to find out where the duplication is originating. I believe that the duplication occurs within sidekiq, though I am not sure why. 

Packet captures indicate that sidekiq is connecting to my smtp server with each email twice (repeating the smtp ID of  the form xxxxxxxxx@phishingfrenzy.mail). Emails are not duplicated when I use synchronous sending (i.e. do not use sidekiq by disabling background email in global settings). I have been intending to write some logs out of phishing_frenzy_mailer.rb (I think this is run by sidekiq, but I don't know Ruby) to see if this is run multiple times. 

I would also love any guidance on this issue.

**Comment by zeknox** [comment] 2015-01-12 02:34
Can you guys tell me if you are sending emails in the foreground or background?  There should be a checkbox in the "Global Settings".

This will tell me if you guys are using sidekiq + redis or not for sending emails.

**Comment by boredaussie** [comment] 2015-01-12 02:44
For me, duplication only occurs via sidekiq + redis. Sending emails in the foreground works fine (no duplication), though it's obviously not preferable, especially with large blasts. As outlined above, I believe the issue is in either sidekiq or the code executed by it. 

Sidekiq logs and the web UI show only one email being sent. However, packet captures show that it is sent twice from sidekiq.

**Comment by zeknox** [comment] 2015-01-12 02:48
Thanks for the additional info. This will help me troubleshoot the issues. I'll have to look further to see what is causing this issue.  This is the file that I would suspect is the culprit but I don't see anything wrong on the surface:

https://github.com/pentestgeek/phishing-frenzy/blob/master/app/workers/mail_worker.rb

**Comment by dalton** [comment] 2015-01-12 02:55
If the mail_worker is able to send out the email, but then fails at some later step, sidekiq will re-queue the job and try it again, sometimes looping multiple times. I suspect that's what happening but it would probably help if people with the bug would post the relevant entries for the sidekiq logs.

**Comment by zeknox** [comment] 2015-01-12 03:04
@dalton is that the case even those we have retry set to false in the worker?

**Comment by boredaussie** [comment] 2015-01-12 03:06
I haven't seen any evidence of retries in the sidekiq logs. For a blast in which I send an email to two targets, I get a log entry like this one:

`2015-01-11T23:24:57.383Z 19836 TID-d7ihk Sidekiq::Extensions::DelayedMailer JID-336f4371cdaaa299cc43b337 INFO: start`
`2015-01-11T23:24:57.387Z 19836 TID-dagv0 Sidekiq::Extensions::DelayedMailer JID-4ed62b443e29253ceef30ce6 INFO: start`
`2015-01-11T23:25:02.426Z 19836 TID-d7ihk Sidekiq::Extensions::DelayedMailer JID-336f4371cdaaa299cc43b337 INFO: done: 5.043 sec`
`2015-01-11T23:25:02.661Z 19836 TID-dagv0 Sidekiq::Extensions::DelayedMailer JID-4ed62b443e29253ceef30ce6 INFO: done: 5.274 sec`

However, this results in four emails emails being sent by the server (traced via packet capture), so each recipient gets the email twice. It's worth noting that you won't be able to reproduce this if you're sending it to gmail or some other clients - it detects the repeated SMTP ID and drops one.

**Comment by dalton** [comment] 2015-01-12 03:13
I think @zeknox is right and we resolved what I'm thinking of by setting retry to false. This is something else.

**Comment by boredaussie** [comment] 2015-01-12 04:53
I've just tested sending this to a newer version of Outlook. It looks like the Exchange server dropped the repeated email upon receipt. This may be why some have not reported issues - if recipients are on a modern Exchange system, Gmail, or some other clients, the duplicated emails are deleted.

**Comment by zeknox** [comment] 2015-01-19 21:33
@dalton any chance you could look into this?

**Comment by zeknox** [comment] 2015-01-22 19:13
Gents- thanks for the feedback on this issue here. Not sure when I will have the CPU cycles to look into this, so anyone lurking from the community please feel free to debug this one. Thanks.

**Comment by DeathsPirate** [comment] 2015-02-02 11:44
I'm getting this too, using sendgrid to send out mails and noticing that the actual amount sent according to SG is more than the campaign list. Anyone have any update on this? Workarounds?

**Comment by verybiigcat** [comment] 2015-02-27 17:19
I believe the issue is due to "deliver" being called in phishing_frenzy_mailer.rb (cast). When using Sidekiq, the "delay.phish" method in the controller automatically calls deliver so it shouldn't be called manually again.

**Comment by zeknox** [comment] 2015-03-02 16:57
@verybiigcat appreciate you looking into this. I think you are correct. There is 2 different deliver methods getting called. One in the email_controller as well as another one in the phishing_frenzy_mailer.

I think we could modify this line from the email_controller to remove deliver and it still should call the mailer properly:

https://github.com/pentestgeek/phishing-frenzy/blob/master/app/controllers/email_controller.rb#L16

**Comment by DeathsPirate** [comment] 2015-03-20 11:40
Is a viable workaround to remove the deliver call from the phishing_frenzy_mailer.rb if I'm using Sidekiq?

**Comment by zeknox** [comment] 2015-03-20 14:32
I don't think removing `deliver` inside the phish_mailer is the proper approach. I still haven't had any CPU cycles to debug this one, but I'm wondering if you could change the `delay` in the email_controller to `perform_async`. This would still create the sidekiq background job, and the `deliver` inside the phish_mailer would still deliver the emails in theory.

**Comment by DeathsPirate** [comment] 2015-03-20 16:55
I'm happy to give that a try ... just about to leave work though so will have a bash at it Monday.

**Comment by zeknox** [comment] 2015-03-20 16:56
Just keep in mind that if your running PF in production mode any code changes require a restart of Apache since the entire application is loaded into memory on startup.  Obviously development mode is best for making and testing changes...

**Comment by DeathsPirate** [comment] 2015-03-26 11:34
Tried changing to `perform_async` but still going out twice.

**Comment by eth0izzle** [comment] 2015-07-14 12:56
Was there a fix for this? I'm experiencing the same issue.

**Comment by zeknox** [comment] 2015-07-14 22:16
No fix currently at this time, perhaps @Meatballs1 has the cycles to debug this one.

**Comment by Meatballs1** [comment] 2015-07-14 22:45
I'm just taking a gander actually there appears to be a related issue:

http://stackoverflow.com/questions/23738538/sidekiq-sent-duplicated-emails-asynchronously

**Comment by Meatballs1** [comment] 2015-07-14 23:05
The issue is that the PhishingFrenzyMailer isn't implementing ActionMailer as expected.

ActionMailer should return a new mail() object. And then you call .deliver on that object as per the docs:

http://guides.rubyonrails.org/action_mailer_basics.html

`UserMailer.welcome_email(@user).deliver_later` (or .deliver)

However our mailer calls `cast` which also tries to deliver the mail. We can see where Sidekiq tries to deliver the mail on line 35:

https://github.com/mperham/sidekiq/blob/2fc1d81cc9691c9232a088f1410c5a27fae5e11f/lib/sidekiq/extensions/action_mailer.rb

I cant see where `app/workers/mail_worker.rb` is actually being used. I suspect it is a redundant file. Deleting it doesn't seem to cause any issues...

**Comment by Meatballs1** [comment] 2015-07-14 23:10
I guess the correct way to fix this is to find the `mail()` class and override the `deliver` method so that it includes the `cast` logic.

**Comment by Meatballs1** [comment] 2015-07-14 23:11
The alternative would be to override the Sidekiq `DelayedMailer.deliver` method so it doesn't actually do anything...

**Comment by Meatballs1** [comment] 2015-07-14 23:33
I think we should probably be registering an observer on the mail object. That way when 

```
 # Your object needs to respond to a single method #delivered_email(mail)
  # which receives the email that is sent.
  def self.register_observer(observer)
    unless @@delivery_notification_observers.include?(observer)
      @@delivery_notification_observers << observer
    end
  end
```

**Comment by Meatballs1** [comment] 2015-07-15 00:33
Hmm the observer has to be a Class (rather than an instance of a class) so we can't associate a blast with it.

Mail objects have `message_id` which should be unique. If we stored a blast with a message id we can observe the object and link them up maybe.

**Comment by Meatballs1** [comment] 2015-07-15 01:43
You can match it all up, but the returned mail object doesn't have any status codes in it :(

**Comment by DeathsPirate** [comment] 2015-07-15 07:58
Yeah I spent ages on this and ended up just living with it.  If clients are
using Outlook/Exchange it's smart enough to ignore one of them.  Not an
ideal solution though so I'm eagerly hoping Meatballs1 will be able to sort
this.

**Comment by boredaussie** [comment] 2015-07-15 08:04
My solution was to use the non-sidekiq / serial sending option. This locks up the browser tab for the duration of the email blast (so it can be hours), but it works reliably without double sending. You can use a second tab to watch the results.

**Comment by Meatballs1** [comment] 2015-07-15 10:15
I think the easiest way to go is to monkey patch Mail::Message.deliver or DelayMailer.deliver :(

**Comment by m7x** [comment] 2017-06-07 17:34
Hello,
I am experiencing the same issue with the latest version of Frenzy. For some reasons the blast log shows only target and one email sent, but then the victim will receive two identical emails. I have tested in a lab with postifix/dovecot and Outlook as a email client.  Please let me know if you want more info, I can provide mail logs if required.

**Comment by zeknox** [comment] 2017-08-15 15:55
@Meatballs1 any chance you'd be able to look at this one again?  I think this is the same issue re-introduced when I had to refactor the Mailer as part of a Rails upgrade.  I'm having issues grasping a solution currently and open to help.  Cheers mate.

**Comment by zeknox** [comment] 2017-08-16 18:34
@Meatballs1 disregard this request.  Pretty sure I've got a fix in place that I'm testing out some more.

**Closed** 2017-09-25 14:16 UTC
Labels: bug

**Comment by nibrasqureshi** [comment] 2022-11-23 11:49
Hi! can someone tell me the exact fix to this issue? I am new to rails 7 and I am facing the same issue! While using sidekiq and Sendgrid to send emails.
