### ISSUE TITLE
Campaign activation error

### ISSUE THREAD

**Issue by WheelsVT** [pentestgeek/phishing-frenzy#154] opened 2015-03-13 02:09 UTC
Whenever I try to activate a campaign the server returns a `Incomplete response received from application` error. I can refresh and resend and the campaign then shows activated, however, the phishing site index.php file is not placed in the public/deployed/campaigns/#/ directory.

Tailing the development.log file shows 
`(7.7ms) COMMIT
Completed 401 Unauthorized in 769ms`

and occationally I'll get a different error about mysql awaiting a result:
```
ActiveRecord::StatementInvalid in CampaignsController#update
Mysql2::Error: This connection is still waiting for a result, try again once you have the result: ROLLBACK
Extracted source (around line #49):

47def update
48  @campaign = Campaign.find(params[:id])
49  if @campaign.update_attributes(params[:campaign])
50    redirect_to @campaign, notice: "Campaign Updated"
51  else
52    @templates = Template.all
```

Running on Ubuntu 14.04 with everything installed as root. I've tried rebuilding from scratch multiple times with the same result. Thanks for your help!

**Comment by zeknox** [comment] 2015-03-13 02:20
Something must have changed with the latest version of Apache and or Ubuntu, because I've seen this issue one other time.  For whatever reason, the /etc/init.d/apache2 reload command is not gracefully reloading the service and terminating active connections.

The work around is to navigate to your global settings and change the apache restart command to `sudo apachectl -k graceful`. This should reload / restart the Apache service gracefully and should resolve your issues.

Additionally, you will need to update your `/etc/sudoers` file to allow www-data to run the new `apachectl -k graceful` command.

**Comment by WheelsVT** [comment] 2015-03-13 02:26
Perfect. That resolved the issue.
Thanks so much for the quick response!!!

**Comment by zeknox** [comment] 2015-03-13 02:27
Let's leave this ticket open here as a reminder for me to update the website with a workaround for this issue.

**Comment by RaiKarnage** [comment] 2015-03-18 07:39
Hey there. It seems that I am getting the same error here. I'm using Kali and configured the use of apachectl over apache2. However, the problem still persists. Any help on this will be appreciated!

**Comment by crybabycarlos** [comment] 2015-03-23 16:57
Getting the same issue when activating a campaign on Ubuntu and I am trying to follow your recommendation zeknox, however, my knowledge of Linux is pretty basic to say the least. What file are you referring to when you say "global settings". And when I modify the sudoers file, I need to modify it to "www-data ALL=(ALL) NOPASSWD: apachectl -k graceful"?

**Comment by zeknox** [comment] 2015-03-23 17:00
Global Settings are inside the web application under Admin -> Global Settings. And yes, your command looks proper for editing the `/etc/sudoers` file to allow PF to restart apache gracefully when making a campaign active.

**Comment by crybabycarlos** [comment] 2015-03-23 17:04
Thanks for the quick response, sorry I overlooked the obvious, I thought you were referring to an environment variable -_-

**Comment by crybabycarlos** [comment] 2015-03-23 17:11
When I launch the campaign it seems to take me to the main login page instead of the template. For the phishing url and fqdn I am using the internal IP address. It is the same address I have configured in Apache and config/application.rb .

**Comment by zeknox** [comment] 2015-03-23 17:20
Dont post that separate issue here, new ticket please.

**Comment by SecurityAddicted** [comment] 2015-04-01 10:36
Same here. Following the apachectl advice hasn't changed anything. Any hint about that?

**Comment by zeknox** [comment] 2015-04-01 14:49
This should be what you want, make sure whatever command you use that you update the sudoers file to allow www-data to restart apache gracefully which makes the phishing site available for use.
http://httpd.apache.org/docs/2.2/stopping.html#graceful

**Comment by SecurityAddicted** [comment] 2015-04-01 15:37
Ok, that may seems weird, but if I use the same apache reload command that I put into the sudoers file (then a working command), the application throws the error, but if I use a non working apache reload command the application works ok (it doesn't reload apache, of course).
Yeah I know, this is weird.

**Comment by zeknox** [comment] 2015-04-02 16:21
For those of you who are still having issues with this, could you please post the details of your `error.log` details when you make a campaign active or inactive. I'm currently having issues reproducing this issue.

For example here is my working version:
<pre>
$ tail -f /var/log/apache2/error.log

App 17071 stdout:  * Reloading web server apache2
[Thu Apr 02 19:12:34.504592 2015] [mpm_event:notice] [pid 12434:tid 139855087773568] AH00493: SIGUSR1 received.  Doing graceful restart
App 17071 stdout:  * 
[ 2015-04-02 19:12:34.5219 17149/7f600de87780 agents/Watchdog/Main.cpp:538 ]: Options: { 'analytics_log_user' => 'nobody', 'default_group' => 'nogroup', 'default_python' => 'python', 'default_ruby' => '/usr/local/rvm/gems/ruby-2.1.1/wrappers/ruby', 'default_user' => 'nobody', 'log_level' => '0', 'max_pool_size' => '6', 'passenger_root' => '/usr/local/rvm/gems/ruby-2.1.1/gems/passenger-4.0.41', 'passenger_version' => '4.0.41', 'pool_idle_time' => '300', 'temp_dir' => '/tmp', 'union_station_gateway_address' => 'gateway.unionstationapp.com', 'union_station_gateway_port' => '443', 'user_switching' => 'true', 'web_server_passenger_version' => '4.0.41', 'web_server_pid' => '12434', 'web_server_type' => 'apache', 'web_server_worker_gid' => '33', 'web_server_worker_uid' => '33' }
[ 2015-04-02 19:12:34.5251 17152/7f62e4701780 agents/HelperAgent/Main.cpp:643 ]: PassengerHelperAgent online, listening at unix:/tmp/passenger.1.0.12434/generation-13/request
[ 2015-04-02 19:12:34.5309 17160/7f7d7f92c780 agents/LoggingAgent/Main.cpp:321 ]: PassengerLoggingAgent online, listening at unix:/tmp/passenger.1.0.12434/generation-13/logging
[ 2015-04-02 19:12:34.5311 17149/7f600de87780 agents/Watchdog/Main.cpp:728 ]: All Phusion Passenger agents started!
[Thu Apr 02 19:12:34.531351 2015] [mpm_event:notice] [pid 12434:tid 139855087773568] AH00489: Apache/2.4.7 (Ubuntu) Phusion_Passenger/4.0.41 configured -- resuming normal operations
[Thu Apr 02 19:12:34.531375 2015] [core:notice] [pid 12434:tid 139855087773568] AH00094: Command line: '/usr/sbin/apache2'
App 17197 stdout: 
[ 2015-04-02 19:12:37.2166 17152/7f62e4609700 Pool2/SmartSpawner.h:301 ]: Preloader for /var/www/phishing-frenzy started on PID 17197, listening on unix:/tmp/passenger.1.0.12434/generation-13/backends/preloader.17197
</pre>

Also, any details about your ubuntu, apache, and passenger could be useful. Here is a list of versions I've put together:

problem
passenger 5.0.6
ubuntu 14.04
apache 2.4.7

no problem
passenger 4.0.41
ubuntu 14.04.2 LTS
apache 2.4.7

no problem
passenger 4.0.41
ubuntu 12.04.5
apache 2.2.6

no problem
passenger 4.0.41
ubuntu 12.04.5
apache 2.2.22

no problem
passenger 5.0.6
ubuntu 14.04.2 LTS
apache 2.4.7

**Comment by SecurityAddicted** [comment] 2015-04-08 09:35
I'm using an Ubuntu 14.04.2 EC2 instance.
To me seems like that during the reload the Passenger process get killed and then the app return the error.
```
$ tailf /var/log/apache2/error.log
[Wed Apr 08 09:24:57.565675 2015] [mpm_prefork:notice] [pid 6546] AH00171: Graceful restart requested, doing restart
[ 2015-04-08 09:24:57.5733 26133/7fe20bfff700 age/Hel/Main.cpp:455 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2015-04-08 09:24:57.5733 26138/7f11c30fa700 age/Log/Main.cpp:346 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2015-04-08 09:24:57.5733 26133/7fe21eef57c0 age/Hel/Main.cpp:814 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2015-04-08 09:24:57.5733 26138/7f11c99047c0 age/Log/Main.cpp:408 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2015-04-08 09:24:57.5734 26138/7f11c30fa700 Ser/Server.h:455 ]: [LoggerAdminServer] Shutdown finished
[ 2015-04-08 09:24:57.5734 26133/7fe20b7fe700 Ser/Server.h:455 ]: [ServerThr.2] Shutdown finished
[ 2015-04-08 09:24:57.5734 26138/7f11c99047c0 age/Log/Main.cpp:433 ]: PassengerAgent logger shutdown finished
[ 2015-04-08 09:24:57.5735 26133/7fe20bfff700 Ser/Server.h:455 ]: [ServerThr.1] Shutdown finished
[ 2015-04-08 09:24:57.5742 26133/7fe20affd700 Ser/Server.h:455 ]: [AdminServer] Shutdown finished
[ 2015-04-08 09:24:57.5771 26133/7fe21eef57c0 age/Hel/Main.cpp:876 ]: PassengerAgent server shutdown finished
[Wed Apr 08 09:24:57.597296 2015] [ssl:warn] [pid 6546] AH01906: RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[ 2015-04-08 09:24:57.6024 26249/7fdf23d307c0 age/Wat/Main.cpp:1264 ]: Starting PassengerAgent watchdog...
[ 2015-04-08 09:24:57.6080 26252/7f5d8c5ef7c0 age/Hel/Main.cpp:891 ]: Starting PassengerAgent server...
[ 2015-04-08 09:24:57.6081 26252/7f5d8c5ef7c0 age/Hel/Main.cpp:234 ]: PassengerAgent server running in multi-application mode.
[ 2015-04-08 09:24:57.6096 26252/7f5d8c5ef7c0 age/Hel/Main.cpp:645 ]: PassengerAgent server online, PID 26252
[ 2015-04-08 09:24:57.6153 26257/7f12812c87c0 age/Log/Main.cpp:439 ]: Starting PassengerAgent logger...
[ 2015-04-08 09:24:57.6158 26257/7f12812c87c0 age/Log/Main.cpp:320 ]: PassengerAgent logger online, PID 26257
[Wed Apr 08 09:24:57.616224 2015] [mpm_prefork:notice] [pid 6546] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.7 OpenSSL/1.0.1f Phusion_Passenger/5.0.5 configured -- resuming normal operations
[Wed Apr 08 09:24:57.616236 2015] [core:notice] [pid 6546] AH00094: Command line: '/usr/sbin/apache2'
```

**Comment by SecurityAddicted** [comment] 2015-04-08 12:23
Problem resolved... I created a pull request for you.

**Comment by zeknox** [comment] 2015-04-15 01:22
PR https://github.com/pentestgeek/phishing-frenzy/pull/163 has been merged to master. Please test it out folks and keep us posted.

**Comment by zeknox** [comment] 2015-05-01 18:51
Bump, could you let us know if PR #163 that is now in master is addressing your issues?

**Comment by SecurityAddicted** [comment] 2015-05-01 19:35
For me it's working perfectly now.

**Closed** 2015-05-15 03:48 UTC
Labels: bug
