### ISSUE TITLE
Some Template Issue

### ISSUE THREAD

**Issue by adityasriv22** [pentestgeek/phishing-frenzy#396] opened 2018-08-17 08:48 UTC
Generic Template Issue: Missing template /var/www/phishing-frenzy/public/uploads/attachment/file/5/intel.html.erb with "mailer". Searched in: * "/var/www/phishing-frenzy/public/uploads/attachment/file/5"

**Comment by adityasriv22** [comment] 2018-08-20 08:37
![screenshot from 2018-08-20 14-06-39](https://user-images.githubusercontent.com/9220248/44329540-55622800-a482-11e8-9a3d-607efd25cf29.png)

I am having this error and i am not able to open the template if someone sends a fake email

**Comment by zeknox** [comment] 2018-09-26 14:27
I'm sorry, but I've been unable to reproduce this specific issue on the supported operating systems.

**Comment by zeknox** [comment] 2018-11-30 15:15
Closing due to unable to reproduce this specific issue. Please re-open if still having this issue.

**Closed by zeknox** 2018-11-30 15:15 UTC
Labels: question
