### ISSUE TITLE
Feature Req: Download Tracking

### ISSUE THREAD

**Issue by Meatballs1** [pentestgeek/phishing-frenzy#205] opened 2015-07-18 12:01 UTC
As well as email open, url clicked, creds entered, it would be good to have an optional file download on the site which can be tracked :)

**Comment by zeknox** [comment] 2016-11-23 01:49
Closing as this is a duplicate of: https://github.com/pentestgeek/phishing-frenzy/issues/315

**Closed by zeknox** 2016-11-23 01:49 UTC
Labels: duplicate, enhancement
